# Generated by Django 4.1.5 on 2023-01-31 02:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="my_api",
            new_name="myapi",
        ),
    ]
