# Generated by Django 4.1.5 on 2023-01-31 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_rename_my_api_myapi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myapi",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
